In [2]:
import numpy as np
B = np.arange(3)
# print
#print np.exp(B)
print(np.sqrt(B))

[0.         1.         1.41421356]


In [7]:
#Return the floor of the input
a = np.floor(10*np.random.random((3,4)))  # 向下取整
print(a)

a.shape
## flatten the array
a.ravel()
a.shape = (6, 2)
#print a 
#print a.T
print(a.resize((2,6)))
print(a)

#If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated:
a.reshape(3,-1)
print(a)

[[5. 1. 5. 4.]
 [9. 3. 6. 3.]
 [8. 5. 4. 6.]]
None
[[5. 1. 5. 4. 9. 3.]
 [6. 3. 8. 5. 4. 6.]]
[[5. 1. 5. 4. 9. 3.]
 [6. 3. 8. 5. 4. 6.]]


In [6]:
a.T

array([[3., 0.],
       [8., 5.],
       [8., 2.],
       [7., 7.],
       [1., 1.],
       [8., 3.]])

In [9]:
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))
print(a)
print('---')
print(b)
print('---')
print(np.hstack((a,b))) # 拼接数组
#np.hstack((a,b))

[[1. 7.]
 [9. 3.]]
---
[[1. 9.]
 [5. 7.]]
---
[[1. 7. 1. 9.]
 [9. 3. 5. 7.]]


In [11]:
np.vstack((a, b))

array([[1., 7.],
       [9., 3.],
       [1., 9.],
       [5., 7.]])

In [21]:
a = np.floor(10*np.random.random((2,12)))
print(a)
print(np.hsplit(a,3))  #分割
print(np.hsplit(a,(3,4)))    # Split a after the third and the fourth column
a = np.floor(10*np.random.random((12,2)))
print(a)
np.vsplit(a,3)

[[3. 3. 2. 9. 2. 7. 4. 4. 6. 4. 0. 6.]
 [9. 1. 6. 7. 3. 1. 6. 8. 6. 5. 4. 7.]]
[array([[3., 3., 2., 9.],
       [9., 1., 6., 7.]]), array([[2., 7., 4., 4.],
       [3., 1., 6., 8.]]), array([[6., 4., 0., 6.],
       [6., 5., 4., 7.]])]
[array([[3., 3., 2.],
       [9., 1., 6.]]), array([[9.],
       [7.]]), array([[2., 7., 4., 4., 6., 4., 0., 6.],
       [3., 1., 6., 8., 6., 5., 4., 7.]])]
[[6. 7.]
 [1. 5.]
 [5. 6.]
 [0. 9.]
 [4. 1.]
 [3. 4.]
 [7. 0.]
 [3. 4.]
 [9. 5.]
 [9. 2.]
 [5. 6.]
 [4. 6.]]


[array([[6., 7.],
        [1., 5.],
        [5., 6.],
        [0., 9.]]), array([[4., 1.],
        [3., 4.],
        [7., 0.],
        [3., 4.]]), array([[9., 5.],
        [9., 2.],
        [5., 6.],
        [4., 6.]])]

In [15]:
x = np.floor(10*np.random.random((2,12)))
x

array([[8., 7., 3., 9., 5., 8., 9., 5., 4., 1., 5., 2.],
       [0., 3., 1., 9., 7., 3., 5., 2., 1., 0., 4., 6.]])

In [24]:
#Simple assignments make no copy of array objects or of their data.
a = np.arange(12)
print(a)
b = a
# a and b are two names for the same ndarray object
print(b is a)
b.shape = 3,4
print(a.shape)
print(id(a))
print(id(b))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
True
(3, 4)
2178561536048
2178561536048


In [43]:
#The view method creates a new array object that looks at the same data.
c = a.view() # 浅复制
c is a
c.shape = 2,6
#print a.shape
c[0,4] = 1234
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [46]:
#The copy method makes a complete copy of the array and its data.
d = a.copy() 
d is a
d[0,0] = 9999
print d 
print a

[[9999    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
