In [14]:
import numpy as np
data = np.sin(np.arange(20)).reshape(5,4)
print( data)
ind = data.argmax(axis=1)  #找到每一行中最大值的索引
print(ind)
data_max = data[range(data.shape[0]), ind]
print(data_max)
all(data_max == data.max(axis=1))

[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]
 [-0.53657292  0.42016704  0.99060736  0.65028784]
 [-0.28790332 -0.96139749 -0.75098725  0.14987721]]
[2 3 0 2 3]
[0.90929743 0.6569866  0.98935825 0.99060736 0.14987721]


True

In [10]:
data.shape[0]

5

In [17]:
a = np.arange(0, 40, 10)
print(a)
b = np.tile(a, (1, 5))  #扩展
print(b)

[ 0 10 20 30]
[[ 0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30]]


a = np.arange(0, 40, 10)
print a
print '---'
b = np.tile(a, (1, 4))
print b
#print a
#print b


In [19]:
a = np.array([[4, 3, 5], [1, 2, 1]])
print(a)
b = np.sort(a, axis=1)
print(b)
#b
#a.sort(axis=1)
#print a
a = np.array([4, 3, 1, 2])
j = np.argsort(a) 
print(j)
print(a[j])

[[4 3 5]
 [1 2 1]]
[[3 4 5]
 [1 1 2]]
[2 3 1 0]
[1 2 3 4]


In [20]:
np.sort(a, axis=0)

array([1, 2, 3, 4])

In [21]:
a

array([4, 3, 1, 2])

In [25]:
a = np.array([[4, 3, 5], [1, 8, 1]])
a

array([[4, 3, 5],
       [1, 8, 1]])

In [26]:
np.sort(a, axis=0)

array([[1, 3, 1],
       [4, 8, 5]])

In [29]:
j = np.argsort(a)

In [31]:
a[j]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [32]:
a = np.array([4, 3, 1, 2])

In [33]:
j = np.argsort(a) #索引

In [34]:
j

array([2, 3, 1, 0], dtype=int64)

In [35]:
a[j]

array([1, 2, 3, 4])

In [36]:
a[j[-1]]

4